<a href="https://colab.research.google.com/github/anjha1/Deep-Learning/blob/main/10_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---

# **TensorFlow Notes**

## **1. Introduction to TensorFlow**

* TensorFlow is an **open-source machine learning framework** developed by **Google**.
* Initially created by the **Google Brain Team** for large-scale numerical computation.
* Built for **high-performance numerical operations** and scalable ML model development.
* Widely used in academic research, industry, and production environments.

---

## **2. Key Features of TensorFlow**

### **A. Flexibility**

* Modular architecture supports both **high-level APIs** (like Keras) and **low-level operations**.
* Enables **custom model building**, layer creation, and fine-grained control.
* Supports dynamic computation graphs (with `tf.function` and AutoGraph).

### **B. Scalability**

* Efficiently scales across:

  * **CPUs**
  * **GPUs**
  * **TPUs**
* Can run on **single devices** or **distributed clusters**.
* Suited for both small and **large-scale ML tasks**.

### **C. Versatile Applications**

TensorFlow is used in a wide range of domains:

* **Computer Vision** (e.g., CNNs for image classification)
* **Natural Language Processing (NLP)** (e.g., transformers, RNNs)
* **Speech Recognition**
* **Recommendation Systems**
* **Time Series Forecasting**
* Robotics and autonomous systems

### **D. Ecosystem & Community**

* Strong ecosystem including:

  * **TensorBoard** (visualization & debugging)
  * **TensorFlow Lite** (mobile/edge deployment)
  * **TensorFlow\.js** (in-browser ML)
  * **TensorFlow Extended (TFX)** (production pipelines)
* Active global community: open-source contributors, researchers, developers.
* Rich set of **pre-trained models**, libraries, and tutorials.

### **E. Integration**

* Works seamlessly with other popular Python libraries like:

  * **NumPy**
  * **Pandas**
  * **Scikit-learn**
* Smooth integration enables **efficient ML workflows** and data preprocessing.

### **F. Deployment Options**

* Models can be deployed to:

  * **Desktop & cloud servers**
  * **Mobile devices** (via TensorFlow Lite)
  * **Edge devices**
  * **TPUs for ultra-fast computation**

---

## **3. Tools and Utilities**

### **TensorBoard**

* A suite of visualization tools for:

  * Monitoring training performance
  * Viewing computation graphs
  * Analyzing model metrics (loss, accuracy, etc.)

### **Model Optimization & Conversion**

* Supports model pruning, quantization for smaller and faster models.
* Convert models for TensorFlow Lite or TensorFlow\.js easily.

---

## **4. Benefits of Using TensorFlow**

* **Production-ready**: Suitable for prototyping and deploying models in production.
* **Cross-platform support**: Run models on web, cloud, mobile, or embedded devices.
* **Continuous development**: Backed by Google with regular updates and improvements.
* **Interoperability**: Compatible with other ML tools and platforms.

---

## **5. Summary for Interviews**

| Topic              | Key Points                                              |
| ------------------ | ------------------------------------------------------- |
| Developed by       | Google Brain Team                                       |
| Open Source        | Yes                                                     |
| Key Strengths      | Flexibility, Scalability, Deployment, Community Support |
| APIs               | High-level (Keras), Low-level (TensorFlow Core)         |
| Deployment Targets | CPU, GPU, TPU, Mobile (Lite), Web (JS), Edge            |
| Applications       | CV, NLP, Speech, Recommendations, Scientific Computing  |
| Tools              | TensorBoard, TFX, TensorFlow Lite, TensorFlow Serving   |
| Integrations       | NumPy, Pandas, Scikit-learn                             |
| Visualization      | TensorBoard                                             |

---





---

# **TensorFlow vs PyTorch: A Detailed Comparison**

| Feature                           | **TensorFlow**                                                                                 | **PyTorch**                                                          |
| --------------------------------- | ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| **Developed By**                  | Google Brain Team                                                                              | Facebook's AI Research Lab (FAIR)                                    |
| **Initial Release**               | 2015                                                                                           | 2016                                                                 |
| **Language Support**              | Python, C++, Java, JavaScript, Go, Swift, etc.                                                 | Primarily Python (with C++ backend)                                  |
| **Ease of Use**                   | Initially complex, improved with Keras integration                                             | Simple and more "Pythonic", intuitive for beginners                  |
| **Computation Graphs**            | Static Graph (Graph defined before execution); <br>Supports **eager execution** (since TF 2.x) | **Dynamic Graph** (defined at runtime — more flexible)               |
| **Debugging**                     | Harder to debug (static graph); TensorBoard helps                                              | Easier to debug using standard Python tools (e.g., `pdb`)            |
| **High-Level APIs**               | `tf.keras` (official high-level API)                                                           | `torch.nn`, `torchvision`, `torchaudio`                              |
| **Deployment Support**            | TensorFlow Lite, TensorFlow\.js, TensorFlow Serving                                            | TorchServe (less mature), ONNX for interoperability                  |
| **Visualization**                 | **TensorBoard** (rich visualization support)                                                   | Basic TensorBoard support, 3rd-party tools like **Weights & Biases** |
| **Mobile/Edge Support**           | **TensorFlow Lite**, TensorFlow\.js                                                            | TorchScript, PyTorch Mobile (less mature)                            |
| **Community & Ecosystem**         | Larger, older ecosystem, more tutorials and tools                                              | Rapidly growing, strong academic adoption                            |
| **Performance Optimization**      | TF-Serving, TFLite, XLA, TensorRT                                                              | TorchScript, JIT, ONNX                                               |
| **Model Export/Interoperability** | TF → SavedModel, TFLite, ONNX                                                                  | PyTorch → TorchScript, ONNX                                          |
| **Industry Adoption**             | Widely used in production at Google, Airbnb, Uber, etc.                                        | Popular in research (NLP, CV), used by FAIR, Tesla, Microsoft        |
| **AutoML Support**                | **AutoKeras**, **TensorFlow AutoML**, TFX                                                      | Limited native support (some via third-party tools)                  |

---

## ✅ **When to Use TensorFlow**

* **Production environments**
* Need for cross-platform deployment (cloud, mobile, web)
* Require strong **tooling** (e.g., TensorBoard, TFX)
* Working with **Google Cloud / TPUs**
* Using pre-built models from **TensorFlow Hub**

## ✅ **When to Use PyTorch**

* Research and rapid prototyping
* Dynamic, flexible model building
* Native Python control and simplicity
* Strong support for **NLP** (e.g., Hugging Face Transformers)
* When you prefer **clearer, readable code**

---

## 🔚 **Summary Table**

| Criteria          | TensorFlow                     | PyTorch                                     |
| ----------------- | ------------------------------ | ------------------------------------------- |
| Best For          | **Production, Deployment**     | **Research, Rapid Prototyping**             |
| Graph Type        | Static + Eager (TF 2.x)        | Dynamic (Imperative)                        |
| Learning Curve    | Moderate (easy with Keras)     | Easier, more intuitive                      |
| Deployment        | Excellent (TFLite, TFX, TF.js) | Improving (TorchScript, ONNX)               |
| Visualization     | Excellent (TensorBoard)        | Good (basic TensorBoard, third-party tools) |
| Debugging         | Harder (static graphs)         | Easier (Python-native)                      |
| Community Support | Older, broader ecosystem       | Growing, very strong in academia            |

---



In [1]:
import tensorflow as tf

print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.18.0
Eager execution is: True
Keras version: 3.8.0


In [3]:
if tf.test.is_gpu_available():
    print('Running on GPU')
else:
    print('Running on CPU')

Running on CPU


In [4]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [5]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [8]:
a.numpy()

np.int32(10)

In [9]:
b=tf.constant(20,dtype=tf.int64)
b

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [10]:
c=tf.constant(10.5)
c

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [11]:
d=tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [12]:
e=tf.constant([1,2,3,4,5])
e

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [13]:
f=tf.constant([[1,2,3],[4,5,6]])
f

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
g=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
g

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [16]:
g.numpy()

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [18]:
g.shape

TensorShape([2, 2, 3])

In [20]:
g.dtype

tf.int32

In [21]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [23]:
h=tf.constant([[1,2,3],[4,5,6]])
i=tf.constant([[7,8,9],[10,11,12]])
k=h+i
k

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [24]:
j=tf.add(h,i)
j

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [25]:
l=tf.constant([1,2,3,4,5])
m=tf.constant([6,7,8,9,10])
n=l*m
n

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 14, 24, 36, 50], dtype=int32)>

In [26]:
o=tf.multiply(l,m)
o

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 14, 24, 36, 50], dtype=int32)>

In [27]:
p=tf.constant([1,2,3,4,5])
q=tf.constant([6,7,8,9,10])
r=p-q
r

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-5, -5, -5, -5, -5], dtype=int32)>

In [28]:
s=tf.subtract(p,q)
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-5, -5, -5, -5, -5], dtype=int32)>

In [29]:
tf.random.uniform(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6153065 , 0.07059848, 0.13884187],
       [0.0674547 , 0.00543714, 0.48613644],
       [0.01256132, 0.54496646, 0.55534005]], dtype=float32)>

In [32]:
tf.random.uniform(shape=(3,3),minval=10,maxval=20)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[19.448727, 14.945351, 12.952901],
       [11.991038, 18.608786, 15.586051],
       [12.515597, 15.420864, 16.756905]], dtype=float32)>

standard normal distribution

In [33]:
tf.random.normal(shape=(3,3),mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.92318815, -1.8595324 , -0.8430857 ],
       [-2.4206526 ,  0.11225755, -0.17725934],
       [ 0.03731887, -0.12617797, -2.6158464 ]], dtype=float32)>

In [34]:
var0=24
var0

24

In [36]:
var1=tf.Variable(24)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>

In [43]:
var2=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
var2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [48]:
var3=tf.Variable([1,2,3,4,5,6,7,8,9,10,11,12],shape=(3,2,2))
var3

ValueError: In this `tf.Variable` creation, the initial value's shape ((12,)) is not compatible with the explicitly supplied `shape` argument ((3, 2, 2)).

In [49]:
var3=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12],shape=(3,2,2))
var3

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [50]:
var4=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=tf.float16)
var4

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float16)>


### 🧠 **TensorFlow Built-in Data Types**

TensorFlow provides a wide variety of built-in data types for flexibility and performance across different machine learning and deep learning tasks.

| **Data Type**   | **Description**                        |
| --------------- | -------------------------------------- |
| `tf.float16`    | 16-bit half-precision floating-point   |
| `tf.float32`    | 32-bit single-precision floating-point |
| `tf.float64`    | 64-bit double-precision floating-point |
| `tf.bfloat16`   | 16-bit truncated floating-point        |
| `tf.complex64`  | 64-bit single-precision complex        |
| `tf.complex128` | 128-bit double-precision complex       |
| `tf.int8`       | 8-bit signed integer                   |
| `tf.uint8`      | 8-bit unsigned integer                 |
| `tf.uint16`     | 16-bit unsigned integer                |
| `tf.uint32`     | 32-bit unsigned integer                |
| `tf.uint64`     | 64-bit unsigned integer                |
| `tf.int16`      | 16-bit signed integer                  |
| `tf.int32`      | 32-bit signed integer                  |
| `tf.int64`      | 64-bit signed integer                  |
| `tf.bool`       | Boolean                                |
| `tf.string`     | String                                 |
| `tf.qint8`      | Quantized 8-bit signed integer         |
| `tf.quint8`     | Quantized 8-bit unsigned integer       |
| `tf.qint16`     | Quantized 16-bit signed integer        |
| `tf.quint16`    | Quantized 16-bit unsigned integer      |
| `tf.qint32`     | Quantized 32-bit signed integer        |
| `tf.resource`   | Handle to a mutable resource           |
| `tf.variant`    | Values of arbitrary types              |

---


---

### ✅ **Default Data Types in TensorFlow**

| **Type**       | **Default Data Type** |
| -------------- | --------------------- |
| Integer        | `tf.int32`            |
| Floating-Point | `tf.float32`          |

These defaults are chosen for a balance between performance and precision.

---



In [51]:
var_reassign=tf.Variable(10.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>

In [52]:
var_reassign.assign(20)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>

In [53]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.33329982,  0.3090235 ],
       [-0.6161683 ,  0.7224309 ]], dtype=float32)>


In [56]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.565612  ,  1.6800135 ],
       [ 0.25597572, -0.70400226]], dtype=float32)>

In [59]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [60]:
t=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [61]:
t.shape

TensorShape([2, 2, 3])

In [63]:
t.reshape(3,4)
t

AttributeError: 'ResourceVariable' object has no attribute 'reshape'

In [64]:
p=tf.reshape(t,(3,4))
p

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [65]:
tf.reshape(t,(6,2))

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [66]:
tf.reshape(t,(1,12))

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]], dtype=int32)>

In [67]:
tf.reshape(t,(12,1))

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int32)>

Ranking (dimensions) of a tensor

The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.

In [68]:
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [72]:
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [73]:
t1=t[1,0,1]
t1

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [74]:
print(t.numpy)

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>>


In [75]:
print(t.numpy())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [79]:
t2=t[1,0,0]
t2

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [81]:
t2=t[1,0,0].numpy()
print(t2)

7


In [84]:
print(tf.size(t).numpy())

12


In [85]:
t.dtype

tf.int32

In [87]:
a=tf.random.uniform(shape=(3,3))
b=tf.random.normal(shape=(3,3))
c=a+b
d=tf.square(c)
e=tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[0.707422   0.80522037 0.22652996]
 [0.07930672 0.41299903 0.6880125 ]
 [0.43504834 0.5090189  0.6798427 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.7929093   0.9662454   0.90695155]
 [ 0.07213974  0.3403845  -0.9852105 ]
 [ 0.7021909  -0.6937862  -0.6422257 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.5003314   1.7714658   1.1334815 ]
 [ 0.15144646  0.7533835  -0.297198  ]
 [ 1.1372392  -0.1847673   0.03761703]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2.2509942e+00 3.1380911e+00 1.2847803e+00]
 [2.2936031e-02 5.6758672e-01 8.8326648e-02]
 [1.2933130e+00 3.4138959e-02 1.4150408e-03]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[4.4831743 5.879465  3.1064527]
 [1.163516  2.124175  0.7428969]
 [3.1181479 0.8312977 1.0383335]], shape=(3, 3), dtype=float32)


In [89]:
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [88]:
t*t

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]]], dtype=int32)>

In [90]:
t+t

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]], dtype=int32)>

In [91]:
t-t

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)>

In [93]:
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [92]:
t4=t*4
t4

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  8, 12],
        [16, 20, 24]],

       [[28, 32, 36],
        [40, 44, 48]]], dtype=int32)>