<a href="https://colab.research.google.com/github/anjha1/Deep-Learning/blob/main/10_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---

# **TensorFlow Notes**

## **1. Introduction to TensorFlow**

* TensorFlow is an **open-source machine learning framework** developed by **Google**.
* Initially created by the **Google Brain Team** for large-scale numerical computation.
* Built for **high-performance numerical operations** and scalable ML model development.
* Widely used in academic research, industry, and production environments.

---

## **2. Key Features of TensorFlow**

### **A. Flexibility**

* Modular architecture supports both **high-level APIs** (like Keras) and **low-level operations**.
* Enables **custom model building**, layer creation, and fine-grained control.
* Supports dynamic computation graphs (with `tf.function` and AutoGraph).

### **B. Scalability**

* Efficiently scales across:

  * **CPUs**
  * **GPUs**
  * **TPUs**
* Can run on **single devices** or **distributed clusters**.
* Suited for both small and **large-scale ML tasks**.

### **C. Versatile Applications**

TensorFlow is used in a wide range of domains:

* **Computer Vision** (e.g., CNNs for image classification)
* **Natural Language Processing (NLP)** (e.g., transformers, RNNs)
* **Speech Recognition**
* **Recommendation Systems**
* **Time Series Forecasting**
* Robotics and autonomous systems

### **D. Ecosystem & Community**

* Strong ecosystem including:

  * **TensorBoard** (visualization & debugging)
  * **TensorFlow Lite** (mobile/edge deployment)
  * **TensorFlow\.js** (in-browser ML)
  * **TensorFlow Extended (TFX)** (production pipelines)
* Active global community: open-source contributors, researchers, developers.
* Rich set of **pre-trained models**, libraries, and tutorials.

### **E. Integration**

* Works seamlessly with other popular Python libraries like:

  * **NumPy**
  * **Pandas**
  * **Scikit-learn**
* Smooth integration enables **efficient ML workflows** and data preprocessing.

### **F. Deployment Options**

* Models can be deployed to:

  * **Desktop & cloud servers**
  * **Mobile devices** (via TensorFlow Lite)
  * **Edge devices**
  * **TPUs for ultra-fast computation**

---

## **3. Tools and Utilities**

### **TensorBoard**

* A suite of visualization tools for:

  * Monitoring training performance
  * Viewing computation graphs
  * Analyzing model metrics (loss, accuracy, etc.)

### **Model Optimization & Conversion**

* Supports model pruning, quantization for smaller and faster models.
* Convert models for TensorFlow Lite or TensorFlow\.js easily.

---

## **4. Benefits of Using TensorFlow**

* **Production-ready**: Suitable for prototyping and deploying models in production.
* **Cross-platform support**: Run models on web, cloud, mobile, or embedded devices.
* **Continuous development**: Backed by Google with regular updates and improvements.
* **Interoperability**: Compatible with other ML tools and platforms.

---

## **5. Summary for Interviews**

| Topic              | Key Points                                              |
| ------------------ | ------------------------------------------------------- |
| Developed by       | Google Brain Team                                       |
| Open Source        | Yes                                                     |
| Key Strengths      | Flexibility, Scalability, Deployment, Community Support |
| APIs               | High-level (Keras), Low-level (TensorFlow Core)         |
| Deployment Targets | CPU, GPU, TPU, Mobile (Lite), Web (JS), Edge            |
| Applications       | CV, NLP, Speech, Recommendations, Scientific Computing  |
| Tools              | TensorBoard, TFX, TensorFlow Lite, TensorFlow Serving   |
| Integrations       | NumPy, Pandas, Scikit-learn                             |
| Visualization      | TensorBoard                                             |

---





---

# **TensorFlow vs PyTorch: A Detailed Comparison**

| Feature                           | **TensorFlow**                                                                                 | **PyTorch**                                                          |
| --------------------------------- | ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| **Developed By**                  | Google Brain Team                                                                              | Facebook's AI Research Lab (FAIR)                                    |
| **Initial Release**               | 2015                                                                                           | 2016                                                                 |
| **Language Support**              | Python, C++, Java, JavaScript, Go, Swift, etc.                                                 | Primarily Python (with C++ backend)                                  |
| **Ease of Use**                   | Initially complex, improved with Keras integration                                             | Simple and more "Pythonic", intuitive for beginners                  |
| **Computation Graphs**            | Static Graph (Graph defined before execution); <br>Supports **eager execution** (since TF 2.x) | **Dynamic Graph** (defined at runtime — more flexible)               |
| **Debugging**                     | Harder to debug (static graph); TensorBoard helps                                              | Easier to debug using standard Python tools (e.g., `pdb`)            |
| **High-Level APIs**               | `tf.keras` (official high-level API)                                                           | `torch.nn`, `torchvision`, `torchaudio`                              |
| **Deployment Support**            | TensorFlow Lite, TensorFlow\.js, TensorFlow Serving                                            | TorchServe (less mature), ONNX for interoperability                  |
| **Visualization**                 | **TensorBoard** (rich visualization support)                                                   | Basic TensorBoard support, 3rd-party tools like **Weights & Biases** |
| **Mobile/Edge Support**           | **TensorFlow Lite**, TensorFlow\.js                                                            | TorchScript, PyTorch Mobile (less mature)                            |
| **Community & Ecosystem**         | Larger, older ecosystem, more tutorials and tools                                              | Rapidly growing, strong academic adoption                            |
| **Performance Optimization**      | TF-Serving, TFLite, XLA, TensorRT                                                              | TorchScript, JIT, ONNX                                               |
| **Model Export/Interoperability** | TF → SavedModel, TFLite, ONNX                                                                  | PyTorch → TorchScript, ONNX                                          |
| **Industry Adoption**             | Widely used in production at Google, Airbnb, Uber, etc.                                        | Popular in research (NLP, CV), used by FAIR, Tesla, Microsoft        |
| **AutoML Support**                | **AutoKeras**, **TensorFlow AutoML**, TFX                                                      | Limited native support (some via third-party tools)                  |

---

## ✅ **When to Use TensorFlow**

* **Production environments**
* Need for cross-platform deployment (cloud, mobile, web)
* Require strong **tooling** (e.g., TensorBoard, TFX)
* Working with **Google Cloud / TPUs**
* Using pre-built models from **TensorFlow Hub**

## ✅ **When to Use PyTorch**

* Research and rapid prototyping
* Dynamic, flexible model building
* Native Python control and simplicity
* Strong support for **NLP** (e.g., Hugging Face Transformers)
* When you prefer **clearer, readable code**

---

## 🔚 **Summary Table**

| Criteria          | TensorFlow                     | PyTorch                                     |
| ----------------- | ------------------------------ | ------------------------------------------- |
| Best For          | **Production, Deployment**     | **Research, Rapid Prototyping**             |
| Graph Type        | Static + Eager (TF 2.x)        | Dynamic (Imperative)                        |
| Learning Curve    | Moderate (easy with Keras)     | Easier, more intuitive                      |
| Deployment        | Excellent (TFLite, TFX, TF.js) | Improving (TorchScript, ONNX)               |
| Visualization     | Excellent (TensorBoard)        | Good (basic TensorBoard, third-party tools) |
| Debugging         | Harder (static graphs)         | Easier (Python-native)                      |
| Community Support | Older, broader ecosystem       | Growing, very strong in academia            |

---



In [134]:
import tensorflow as tf

print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.18.0
Eager execution is: True
Keras version: 3.8.0


In [135]:
if tf.test.is_gpu_available():
    print('Running on GPU')
else:
    print('Running on CPU')

Running on CPU


In [136]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [137]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [138]:
a.numpy()

np.int32(10)

In [139]:
b=tf.constant(20,dtype=tf.int64)
b

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [140]:
c=tf.constant(10.5)
c

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [141]:
d=tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [142]:
e=tf.constant([1,2,3,4,5])
e

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [143]:
f=tf.constant([[1,2,3],[4,5,6]])
f

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [144]:
g=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
g

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [145]:
g.numpy()

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [146]:
g.shape

TensorShape([2, 2, 3])

In [147]:
g.dtype

tf.int32

In [148]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [149]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [150]:
h=tf.constant([[1,2,3],[4,5,6]])
i=tf.constant([[7,8,9],[10,11,12]])
k=h+i
k

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [151]:
j=tf.add(h,i)
j

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [152]:
l=tf.constant([1,2,3,4,5])
m=tf.constant([6,7,8,9,10])
n=l*m
n

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 14, 24, 36, 50], dtype=int32)>

In [153]:
o=tf.multiply(l,m)
o

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 14, 24, 36, 50], dtype=int32)>

In [154]:
p=tf.constant([1,2,3,4,5])
q=tf.constant([6,7,8,9,10])
r=p-q
r

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-5, -5, -5, -5, -5], dtype=int32)>

In [155]:
s=tf.subtract(p,q)
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-5, -5, -5, -5, -5], dtype=int32)>

In [156]:
tf.random.uniform(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.95199645, 0.333354  , 0.11390233],
       [0.37526596, 0.93960536, 0.9886317 ],
       [0.04141045, 0.26525903, 0.17588627]], dtype=float32)>

In [157]:
tf.random.uniform(shape=(3,3),minval=10,maxval=20)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[15.183206 , 14.682508 , 17.889797 ],
       [12.782326 , 14.226822 , 17.502586 ],
       [19.003052 , 11.713728 , 13.1134405]], dtype=float32)>

standard normal distribution

In [158]:
tf.random.normal(shape=(3,3),mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7490088 ,  0.72534466, -0.9873869 ],
       [ 0.47794145, -0.97704947, -0.08037011],
       [-0.0453853 ,  0.8354204 , -1.1092433 ]], dtype=float32)>

In [159]:
var0=24
var0

24

In [160]:
var1=tf.Variable(24)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>

In [161]:
var2=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
var2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [162]:
# var3=tf.Variable([1,2,3,4,5,6,7,8,9,10,11,12],shape=(3,2,2))
# var3

In [163]:
var3=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12],shape=(3,2,2))
var3

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [164]:
var4=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=tf.float16)
var4

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float16)>


### 🧠 **TensorFlow Built-in Data Types**

TensorFlow provides a wide variety of built-in data types for flexibility and performance across different machine learning and deep learning tasks.

| **Data Type**   | **Description**                        |
| --------------- | -------------------------------------- |
| `tf.float16`    | 16-bit half-precision floating-point   |
| `tf.float32`    | 32-bit single-precision floating-point |
| `tf.float64`    | 64-bit double-precision floating-point |
| `tf.bfloat16`   | 16-bit truncated floating-point        |
| `tf.complex64`  | 64-bit single-precision complex        |
| `tf.complex128` | 128-bit double-precision complex       |
| `tf.int8`       | 8-bit signed integer                   |
| `tf.uint8`      | 8-bit unsigned integer                 |
| `tf.uint16`     | 16-bit unsigned integer                |
| `tf.uint32`     | 32-bit unsigned integer                |
| `tf.uint64`     | 64-bit unsigned integer                |
| `tf.int16`      | 16-bit signed integer                  |
| `tf.int32`      | 32-bit signed integer                  |
| `tf.int64`      | 64-bit signed integer                  |
| `tf.bool`       | Boolean                                |
| `tf.string`     | String                                 |
| `tf.qint8`      | Quantized 8-bit signed integer         |
| `tf.quint8`     | Quantized 8-bit unsigned integer       |
| `tf.qint16`     | Quantized 16-bit signed integer        |
| `tf.quint16`    | Quantized 16-bit unsigned integer      |
| `tf.qint32`     | Quantized 32-bit signed integer        |
| `tf.resource`   | Handle to a mutable resource           |
| `tf.variant`    | Values of arbitrary types              |

---


---

### ✅ **Default Data Types in TensorFlow**

| **Type**       | **Default Data Type** |
| -------------- | --------------------- |
| Integer        | `tf.int32`            |
| Floating-Point | `tf.float32`          |

These defaults are chosen for a balance between performance and precision.

---



In [165]:
var_reassign=tf.Variable(10.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>

In [166]:
var_reassign.assign(20)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>

In [167]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.55071  , -1.1586068],
       [-0.5813214,  1.1665632]], dtype=float32)>


In [168]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.73980004, -0.5583925 ],
       [ 0.28412685, -1.8302507 ]], dtype=float32)>

In [169]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [170]:
t=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [171]:
t.shape

TensorShape([2, 2, 3])

In [172]:
# t.reshape(3,4)
# t

In [173]:
p=tf.reshape(t,(3,4))
p

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [174]:
tf.reshape(t,(6,2))

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [175]:
tf.reshape(t,(1,12))

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]], dtype=int32)>

In [176]:
tf.reshape(t,(12,1))

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int32)>

Ranking (dimensions) of a tensor

The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.

In [177]:
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [178]:
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [179]:
t1=t[1,0,1]
t1

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [180]:
print(t.numpy)

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>>


In [181]:
print(t.numpy())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [182]:
t2=t[1,0,0]
t2

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [183]:
t2=t[1,0,0].numpy()
print(t2)

7


In [184]:
print(tf.size(t).numpy())

12


In [185]:
t.dtype

tf.int32

In [186]:
a=tf.random.uniform(shape=(3,3))
b=tf.random.normal(shape=(3,3))
c=a+b
d=tf.square(c)
e=tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[0.15417409 0.18370557 0.38594723]
 [0.9911449  0.3248955  0.97487485]
 [0.9964806  0.3471241  0.6219872 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.8126164  -1.1951717   0.08960218]
 [-1.087855    0.1914694   0.7926005 ]
 [ 1.1343883   0.5155506  -0.71300524]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.9667905  -1.0114661   0.4755494 ]
 [-0.09671009  0.51636493  1.7674754 ]
 [ 2.130869    0.8626747  -0.09101802]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.93468386 1.0230638  0.22614723]
 [0.00935284 0.26663274 3.123969  ]
 [4.540602   0.7442077  0.00828428]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2.6294913  0.36368537 1.6088979 ]
 [0.90781915 1.6759244  5.8560505 ]
 [8.422182   2.36949    0.91300124]], shape=(3, 3), dtype=float32)


In [187]:
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [188]:
t*t

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]]], dtype=int32)>

In [189]:
t+t

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]], dtype=int32)>

In [190]:
t-t

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)>

In [191]:
t

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [192]:
t4=t*4
t4

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  8, 12],
        [16, 20, 24]],

       [[28, 32, 36],
        [40, 44, 48]]], dtype=int32)>

In [193]:
m1=tf.constant([[1,2,3],[4,5,6]])
m1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [194]:
m2=tf.constant([[1,2],[3,4],[5,6]])
m2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [195]:
matrix_multiplication=tf.matmul(m1,m2)
matrix_multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [196]:
m1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [197]:
tf.transpose(m1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

dtype-float32=>int64

In [204]:
m4=tf.constant([[1.0,2,3],[4,5,6]])
m4

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [206]:
m3=tf.cast(m1,dtype=tf.int64)
m3

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

With Truncation

In [208]:
tf.cast(tf.constant(4.9),dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

**Declaring Ragged tensors**

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths. There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.


### The following example shows how to declare a constant ragged array and the lengths of the individual slices:

In [209]:
ragged=tf.ragged.constant([[1,2,3],[4,5],[6]])
ragged

<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>

In [210]:
ragged1=tf.ragged.constant([[1,2,3,4],[],[4,5,7],[6],[8,9]])
ragged1

<tf.RaggedTensor [[1, 2, 3, 4], [], [4, 5, 7], [6], [8, 9]]>

In [215]:
ragged1[0:]

<tf.RaggedTensor [[1, 2, 3, 4], [], [4, 5, 7], [6], [8, 9]]>

In [216]:
ragged1[1:]

<tf.RaggedTensor [[], [4, 5, 7], [6], [8, 9]]>

In [218]:
ragged1[1:3]

<tf.RaggedTensor [[], [4, 5, 7]]>

In [219]:
ragged1[-1:]

<tf.RaggedTensor [[8, 9]]>

In [220]:
ragged1[-2:]

<tf.RaggedTensor [[6], [8, 9]]>

In [221]:
ragged1[-4:-2]

<tf.RaggedTensor [[], [4, 5, 7]]>

In [222]:
ragged1[0]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [223]:
ragged1[3]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([6], dtype=int32)>