<a href="https://colab.research.google.com/github/anjha1/Deep-Learning/blob/main/12_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



### **PyTorch -**

#### **Introduction**

* PyTorch is an **open-source machine learning framework**.
* Mainly used for **developing and training deep learning models**.
* Developed by **Facebook's AI Research Lab** and released in **2016**.
* Offers a **flexible and dynamic approach** to building neural networks.
* Popular among researchers and developers.

#### **Key Features**

1. **Dynamic Computational Graphs**

   * Graphs are **built and modified on-the-fly** as the program runs.
   * Allows for **intuitive and flexible** model development.
   * Supports standard **Python control flow** and easy debugging.

2. **Automatic Differentiation**

   * Efficient computation of **gradients for backpropagation**.
   * Supports **data loading**, **model building**, **optimization**, and **evaluation**.

3. **GPU Acceleration**

   * Enables training on **GPUs** to **speed up computations**.
   * Backed by a **large and active community** with many tutorials and pre-trained models.

4. **Comparison with TensorFlow**

   * TensorFlow: uses **static computation graphs**.
   * PyTorch: uses **dynamic graphs** for more **flexibility and ease of use**.

#### **Use in Industry and Research**

* **Widely used in research**.
* Gaining popularity in **industry applications**.
* Provides a **user-friendly platform** for building deep learning models.

---




---

## 🔥 **PyTorch - In-Depth**

---

### **1. PyTorch Architecture Overview**

* **Core Components**:

  1. **Tensors** – Multidimensional arrays, like NumPy arrays but with GPU support.
  2. **Autograd** – Automatic differentiation engine for backpropagation.
  3. **nn.Module** – Base class for all neural networks.
  4. **torch.optim** – Optimization algorithms (SGD, Adam, etc.).
  5. **Data utilities** – `torch.utils.data.Dataset` & `DataLoader` for handling data.

* **Workflow**:

  * Define model using `nn.Module`
  * Forward pass → loss calculation
  * Backward pass using `autograd`
  * Optimizer updates parameters

---

### **2. Tensors in PyTorch**

* Similar to **NumPy arrays**, but can run on **GPU** using `.to("cuda")` or `.cuda()`.

* Created using:

  ```python
  x = torch.tensor([1.0, 2.0])
  y = torch.zeros(2, 3)
  z = torch.rand(4, 4)
  ```

* **Operations**: element-wise, matrix multiplication, reshaping (`.view()` or `.reshape()`), etc.

* **Device control**:

  ```python
  device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
  x = x.to(device)
  ```

---

### **3. Autograd - Automatic Differentiation**

* **`requires_grad=True`** tracks computation for automatic differentiation.

* Builds **Dynamic Computation Graph** at runtime.

* Example:

  ```python
  x = torch.tensor([2.0], requires_grad=True)
  y = x**2
  y.backward()
  print(x.grad)  # Output: tensor([4.])
  ```

* **`.backward()`** computes gradients.

* Use **`with torch.no_grad():`** to disable gradient tracking during inference.

---

### **4. `nn.Module` and Model Building**

* Every model in PyTorch is a subclass of `nn.Module`.

#### **Example:**

```python
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.linear = nn.Linear(10, 1)

    def forward(self, x):
        return self.linear(x)
```

* Key methods:

  * `__init__()`: define layers
  * `forward()`: define forward pass

---

### **5. Optimizers (torch.optim)**

* PyTorch provides various optimizers:

  * `SGD`, `Adam`, `RMSprop`, etc.

* Example:

  ```python
  optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
  ```

* Steps:

  1. `optimizer.zero_grad()`
  2. `loss.backward()`
  3. `optimizer.step()`

---

### **6. Data Loading Utilities**

* **`Dataset`**: Custom data logic
* **`DataLoader`**: Batches, shuffling, multiprocessing
* Example:

  ```python
  from torch.utils.data import DataLoader, Dataset

  class MyDataset(Dataset):
      def __init__(self):
          self.data = torch.randn(100, 10)

      def __len__(self):
          return len(self.data)

      def __getitem__(self, idx):
          return self.data[idx]

  loader = DataLoader(MyDataset(), batch_size=32, shuffle=True)
  ```

---

### **7. Training Loop Structure**

```python
for epoch in range(epochs):
    for inputs, targets in dataloader:
        outputs = model(inputs)
        loss = criterion(outputs, targets)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```

---

### ✅ **Tips for Beginners**

* Use `.to(device)` to move model and tensors to GPU.
* Track gradients only when training (not during inference).
* Use **TensorBoard**, **WandB**, or **Matplotlib** to monitor training.
* Save models with `torch.save()` and load using `torch.load()`.

---




In [27]:
import torch

### Tensors
At its core. PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [28]:
t1=torch.tensor(6.0)
t1

tensor(6.)

In [29]:
t1.dtype

torch.float32

**Vector**

In [30]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

**Matrix**

In [31]:
t3=torch.tensor([[5,6,7],
                [8,9,2],
                [1,2,3]])
t3

tensor([[5, 6, 7],
        [8, 9, 2],
        [1, 2, 3]])

In [32]:
t3.shape

torch.Size([3, 3])

**3-Dimensional-Array**

In [33]:
t4 = torch.tensor([[[1,2,3],[4,5,6],[8,9,10]],[[9,8,7],[6,5,4],[3,2,1]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 8,  9, 10]],

        [[ 9,  8,  7],
         [ 6,  5,  4],
         [ 3,  2,  1]]])

In [34]:
t4.ndim

3

In [35]:
t1

tensor(6.)

In [36]:
t1.shape

torch.Size([])

In [37]:
t1.size()

torch.Size([])

In [38]:
t2.shape

torch.Size([4])

In [39]:
t2.size()

torch.Size([4])

In [40]:
t4.shape

torch.Size([2, 3, 3])

In [41]:
t4.size()

torch.Size([2, 3, 3])

---

## 🧮 **Tensor Operations and Gradients in PyTorch**

### **1. Creating Tensors**


In [42]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

* `x`, `w`, and `b` are all scalar tensors (single float values).
* `w` and `b` have `requires_grad=True`, which tells PyTorch to **track gradients** for them (useful for autograd).



### **2. Arithmetic Operation**

In [43]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)


* Combines tensors using standard arithmetic.

* Value of `y`:
  $y = w \times x + b = 4 \times 3 + 5 = 17$

* PyTorch automatically tracks this computation for backpropagation.

---

### **3. Gradient Computation using Autograd**

In [44]:
y.backward()

* Computes the **derivatives of `y` w\.r.t. tensors with `requires_grad=True`**, i.e., `w` and `b`.

* This uses PyTorch's **autograd** system (automatic differentiation engine).

---

### ✅ **Key Concept: Autograd**

* PyTorch keeps track of operations using a **dynamic computation graph**.
* `.backward()` triggers the computation of gradients.
* After `.backward()`, you can access gradients via:

## 🧠 **Viewing Gradients in PyTorch**

### **1. Accessing Gradients**

* PyTorch stores computed gradients in the `.grad` attribute of tensors:

In [45]:
print('dy/dx:', x.grad)  # None
print('dy/dw:', w.grad)  # tensor(3.)
print('dy/db:', b.grad)  # tensor(1.)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)



### **2. Explanation of Gradient Values**

| Derivative | Value  | Reason                                                     |
| ---------- | ------ | ---------------------------------------------------------- |
| dy/dx      | `None` | `x` does **not** have `requires_grad=True`, so no gradient |
| dy/dw      | `3.`   | Gradient of `y = wx + b` w\.r.t. `w` is `x = 3`            |
| dy/db      | `1.`   | Gradient of `y = wx + b` w\.r.t. `b` is `1` (∂y/∂b = 1)    |

---

### ✅ **Key Notes:**

* `.grad` gives **partial derivatives** of output w\.r.t. each tensor with `requires_grad=True`.
* `x.grad` is `None` because we didn’t set `requires_grad=True` for `x`.
* The term **"grad"** is short for **gradient**, which means derivative (commonly used in ML).

---




## 🧮 PyTorch Tensor Functions

### 🔹 1. Creating a Tensor with a Fixed Value

----

📌 This creates a **3×2 tensor** where **every element is 42**.

In [46]:
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

### 🔹 2. Tensor Concatenation

In [53]:
t_new=torch.tensor([[5,6],
                [8,2],
                [1,2]])
t_new,t6

(tensor([[5, 6],
         [8, 2],
         [1, 2]]),
 tensor([[42, 42],
         [42, 42],
         [42, 42]]))

In [52]:
t7 = torch.cat((t_new, t6))
t7

tensor([[ 5,  6],
        [ 8,  2],
        [ 1,  2],
        [42, 42],
        [42, 42],
        [42, 42]])


📌 `torch.cat()` joins tensors **along the first dimension (rows)** if not specified otherwise.

---

## ✅ Summary:

| Function                 | Description                                           |
| ------------------------ | ----------------------------------------------------- |
| `torch.full(shape, val)` | Creates a tensor filled with the given constant `val` |
| `torch.cat(tensors)`     | Concatenates tensors with compatible shapes           |

🧠 Make sure the tensors have **matching dimensions except along the axis you're concatenating** (default is `dim=0`).

---



In [54]:
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.9894,  0.9093],
        [ 0.8415,  0.9093],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [55]:
t9=torch.reshape(t8,(3,2,2))
t9

tensor([[[-0.9589, -0.2794],
         [ 0.9894,  0.9093]],

        [[ 0.8415,  0.9093],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

You can learn more about tensor operations here: [https://pytorch.org/docs/stable/torch.html](https://pytorch.org/docs/stable/torch.html). Experiment with some more tensor functions and operations using the empty cells below.

---

## 🔄 Interoperability with NumPy (PyTorch + NumPy)

### 🔹 NumPy kya hai?

**NumPy** is a powerful library for numerical computing in Python.

**Used with:**

* **Pandas** – Data analysis
* **Matplotlib** – Visualization
* **OpenCV** – Image processing

**Why use with PyTorch?**

> PyTorch doesn't reinvent the wheel — it works well with NumPy arrays to benefit from Python’s existing data science ecosystem.

---

### 🔸 NumPy Array Creation Example

In [58]:
import numpy as np

x = np.array([[1, 2], [3, 4.1]])
x

array([[1. , 2. ],
       [3. , 4.1]])


### 🔸 Converting NumPy array to PyTorch Tensor

In [59]:
y = torch.from_numpy(x)
y

tensor([[1.0000, 2.0000],
        [3.0000, 4.1000]], dtype=torch.float64)

> ✅ `torch.from_numpy()` **shares memory** with NumPy — meaning changes in one reflect in the other unless explicitly copied.

---

## ✅ Summary Table

| Operation       | PyTorch Code                 | Notes                   |
| --------------- | ---------------------------- | ----------------------- |
| NumPy → PyTorch | `torch.from_numpy(np_array)` | Shares memory (no copy) |
| PyTorch → NumPy | `tensor.numpy()`             | Must be CPU tensor      |

---