<a href="https://colab.research.google.com/github/anjha1/Deep-Learning/blob/main/7_Load_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing Libraries
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import os

In [5]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [7]:
path_name_model = '/content/drive/MyDrive/New Colab Notebooks/Deep Learning/6. Callback Functions/TRAINED_MODEL/Model_2025_05_21_08_16_56_.h5'

loaded_model = tf.keras.models.load_model(path_name_model)

In [8]:
mnist = tf.keras.datasets.mnist
(X_train_full, y_train_full), (X_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [9]:
loaded_model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9701 - loss: 15.8184


[12.818806648254395, 0.9764000177383423]

In [13]:
actual = y_test[:3]
actual

array([7, 2, 1], dtype=uint8)

In [16]:
x_new = X_test[:3]
x_new = x_new / 255.0
y_prob = loaded_model.predict(x_new)
y_prob.round(3)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   ,
        0.   ],
       [0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.998, 0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.   ,
        0.   ]], dtype=float32)

In [18]:
y_pred = np.argmax(y_prob, axis = -1)
y_pred

array([7, 2, 1])