<a href="https://colab.research.google.com/github/anjha1/Deep-Learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



### **PyTorch -**

#### **Introduction**

* PyTorch is an **open-source machine learning framework**.
* Mainly used for **developing and training deep learning models**.
* Developed by **Facebook's AI Research Lab** and released in **2016**.
* Offers a **flexible and dynamic approach** to building neural networks.
* Popular among researchers and developers.

#### **Key Features**

1. **Dynamic Computational Graphs**

   * Graphs are **built and modified on-the-fly** as the program runs.
   * Allows for **intuitive and flexible** model development.
   * Supports standard **Python control flow** and easy debugging.

2. **Automatic Differentiation**

   * Efficient computation of **gradients for backpropagation**.
   * Supports **data loading**, **model building**, **optimization**, and **evaluation**.

3. **GPU Acceleration**

   * Enables training on **GPUs** to **speed up computations**.
   * Backed by a **large and active community** with many tutorials and pre-trained models.

4. **Comparison with TensorFlow**

   * TensorFlow: uses **static computation graphs**.
   * PyTorch: uses **dynamic graphs** for more **flexibility and ease of use**.

#### **Use in Industry and Research**

* **Widely used in research**.
* Gaining popularity in **industry applications**.
* Provides a **user-friendly platform** for building deep learning models.

---




---

## 🔥 **PyTorch - In-Depth**

---

### **1. PyTorch Architecture Overview**

* **Core Components**:

  1. **Tensors** – Multidimensional arrays, like NumPy arrays but with GPU support.
  2. **Autograd** – Automatic differentiation engine for backpropagation.
  3. **nn.Module** – Base class for all neural networks.
  4. **torch.optim** – Optimization algorithms (SGD, Adam, etc.).
  5. **Data utilities** – `torch.utils.data.Dataset` & `DataLoader` for handling data.

* **Workflow**:

  * Define model using `nn.Module`
  * Forward pass → loss calculation
  * Backward pass using `autograd`
  * Optimizer updates parameters

---

### **2. Tensors in PyTorch**

* Similar to **NumPy arrays**, but can run on **GPU** using `.to("cuda")` or `.cuda()`.

* Created using:

  ```python
  x = torch.tensor([1.0, 2.0])
  y = torch.zeros(2, 3)
  z = torch.rand(4, 4)
  ```

* **Operations**: element-wise, matrix multiplication, reshaping (`.view()` or `.reshape()`), etc.

* **Device control**:

  ```python
  device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
  x = x.to(device)
  ```

---

### **3. Autograd - Automatic Differentiation**

* **`requires_grad=True`** tracks computation for automatic differentiation.

* Builds **Dynamic Computation Graph** at runtime.

* Example:

  ```python
  x = torch.tensor([2.0], requires_grad=True)
  y = x**2
  y.backward()
  print(x.grad)  # Output: tensor([4.])
  ```

* **`.backward()`** computes gradients.

* Use **`with torch.no_grad():`** to disable gradient tracking during inference.

---

### **4. `nn.Module` and Model Building**

* Every model in PyTorch is a subclass of `nn.Module`.

#### **Example:**

```python
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.linear = nn.Linear(10, 1)

    def forward(self, x):
        return self.linear(x)
```

* Key methods:

  * `__init__()`: define layers
  * `forward()`: define forward pass

---

### **5. Optimizers (torch.optim)**

* PyTorch provides various optimizers:

  * `SGD`, `Adam`, `RMSprop`, etc.

* Example:

  ```python
  optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
  ```

* Steps:

  1. `optimizer.zero_grad()`
  2. `loss.backward()`
  3. `optimizer.step()`

---

### **6. Data Loading Utilities**

* **`Dataset`**: Custom data logic
* **`DataLoader`**: Batches, shuffling, multiprocessing
* Example:

  ```python
  from torch.utils.data import DataLoader, Dataset

  class MyDataset(Dataset):
      def __init__(self):
          self.data = torch.randn(100, 10)

      def __len__(self):
          return len(self.data)

      def __getitem__(self, idx):
          return self.data[idx]

  loader = DataLoader(MyDataset(), batch_size=32, shuffle=True)
  ```

---

### **7. Training Loop Structure**

```python
for epoch in range(epochs):
    for inputs, targets in dataloader:
        outputs = model(inputs)
        loss = criterion(outputs, targets)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```

---

### ✅ **Tips for Beginners**

* Use `.to(device)` to move model and tensors to GPU.
* Track gradients only when training (not during inference).
* Use **TensorBoard**, **WandB**, or **Matplotlib** to monitor training.
* Save models with `torch.save()` and load using `torch.load()`.

---




In [1]:
import torch

### Tensors
At its core. PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [2]:
t1=torch.tensor(6.0)
t1

tensor(6.)

In [3]:
t1.dtype

torch.float32

**Vector**

In [4]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

**Matrix**

In [8]:
t3=torch.tensor([[5,6,7],
                [8,9,2],
                [1,2,3]])
t3

tensor([[5, 6, 7],
        [8, 9, 2],
        [1, 2, 3]])

In [7]:
t3.shape

torch.Size([3, 3])

**3-Dimensional-Array**

In [12]:
t4 = torch.tensor([[[1,2,3],[4,5,6],[8,9,10]],[[9,8,7],[6,5,4],[3,2,1]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 8,  9, 10]],

        [[ 9,  8,  7],
         [ 6,  5,  4],
         [ 3,  2,  1]]])

In [13]:
t4.ndim

3

In [14]:
t1

tensor(6.)

In [15]:
t1.shape

torch.Size([])

In [17]:
t1.size()

torch.Size([])

In [21]:
t2.shape

torch.Size([4])

In [23]:
t2.size()

torch.Size([4])

In [18]:
t4.shape

torch.Size([2, 3, 3])

In [20]:
t4.size()

torch.Size([2, 3, 3])